### ISSUE TITLE
Call to undefined method NamelessCoder\Fluid3Demo\Introspection::getComponentName() 

### ISSUE THREAD

**Issue by jonaseberle** [NamelessCoder/fluid-3-demo#2]
Thank you for this demo. It is really well written and informative. I also like the new concepts and improvements in Fluid 3. A hardened parser is what I am looking forward to most. 

When accessing `GET /?component=demo:component`:

```
 - Uncaught Error: Call to undefined method NamelessCoder\Fluid3Demo\Introspection::getComponentName() in /home/jonas/src/github.com/NamelessCoder/fluid-3-demo/src/Introspection.php:162
Stack trace:
#0 [internal function]: NamelessCoder\Fluid3Demo\Introspection->getPath()
#1 /home/jonas/src/github.com/NamelessCoder/fluid-3-demo/vendor/typo3fluid/fluid/src/Core/Variables/StandardVariableProvider.php(244): call_user_func_array()
#2 /home/jonas/src/github.com/NamelessCoder/fluid-3-demo/vendor/typo3fluid/fluid/src/Core/Variables/StandardVariableProvider.php(203): TYPO3Fluid\Fluid\Core\Variables\StandardVariableProvider->extractWithAccessor()
#3 /home/jonas/src/github.com/NamelessCoder/fluid-3-demo/vendor/typo3fluid/fluid/src/Core/Variables/StandardVariableProvider.php(126): TYPO3Fluid\Fluid\Core\Variables\StandardVariableProvider->extractSingleValue()
#4 /home/jonas/src/github.com/NamelessCoder/fluid-3-demo/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ObjectAccessorNode.php(49): TYPO3Fluid\Fluid\Core\Variables in /home/jonas/src/github.com/NamelessCoder/fluid-3-demo/src/Introspection.php on line 162

**Comment by NamelessCoder** [comment]
Thanks for the kind words and the bug report - I've fixed the issue (caused by a method renamed on the ComponentInterface but not renamed on the Introspection class which partially mimics a Component).
